services:
  xray:
    image: ghcr.io/grifonsk/xrayclient:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "10808:10808"
    volumes:
      - xray_data:/mnt/xrayclient/config

volumes:
  xray_data:
