services:
  xray:
    image: ghcr.io/grifonsk/xrayclient:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "10888:10808"
      - "10890:10810"
      - "10889:8080"
    volumes:
      - /etc/docker/xrayclienttest:/mnt/xrayclient/config
